import numpy as np
from pathlib import Path
from typing import Optional
from numpy.typing import NDArray
from functools import cached_property
from transformers import AutoTokenizer
from sentence_transformers.SentenceTransformer import SentenceTransformer
from sentence_transformers.cross_encoder import CrossEncoder

from threading import Lock
from typing import ClassVar


from config import settings


def _build_embedding_model():
    if settings.USE_VLLM_EMBEDDING:
        from inference.vllm_client import VLLMEmbeddingClient
        return VLLMEmbeddingClient()
    return EmbeddingModelSingleton()


# Resolved after EmbeddingModelSingleton is defined below; call get_embedding_model() to access.
_embedding_model = None


def get_embedding_model():
    global _embedding_model
    if _embedding_model is None:
        _embedding_model = _build_embedding_model()
    return _embedding_model

class SingletonPattern(type):
    """
    This is a thread-safe implementation of Singleton.
    """
    _instances: ClassVar = {}
    _lock: Lock = Lock()

    def __call__(cls, *args, **kwargs):
        """
        Possible changes to the value of the `__init__` argument do not affect
        the returned instance.
        """
        with cls._lock:
            if cls not in cls._instances:
                instance = super().__call__(*args, **kwargs)
                cls._instances[cls] = instance

        return cls._instances[cls]



class EmbeddingModelSingleton(metaclass=SingletonPattern):
    """
    A singleton class that provides a pre-trained transformer model for generating embeddings of input text.
    """

    def __init__(
            self,
            model_id: str = settings.TEXT_EMBEDDING_MODEL_ID,
            device: str = settings.RAG_MODEL_DEVICE,
            cache_dir: Optional[Path] = None, # where to store model files
        ) -> None:
        
        self._model_id = model_id
        self._device = device

        self._model = SentenceTransformer(
            self._model_id,
            device=self._device,
            cache_folder=str(cache_dir) if cache_dir else None,
            local_files_only=True,
        )
        self._model.eval()

    @property
    def model_id(self) -> str:
        """
        Returns -> (str): The identifier of the pre-trained transformer model to use.
        """
        return self._model_id

    @cached_property
    def embedding_size(self) -> int:
        """
        Returns -> (int): The size of the embeddings generated by the model.
        """
        dummy_embedding = self._model.encode("")
        return dummy_embedding.shape[0]

    @property
    def max_input_length(self) -> int:
        """
        Returns -> (int): The maximum length of input text to tokenize.
        """
        return self._model.max_seq_length

    @property
    def tokenizer(self) -> AutoTokenizer:
        """
        Returns -> (AutoTokenizer): The tokenizer used to tokenize input text.
        """
        return self._model.tokenizer

    def __call__(
            self, 
            input_text: str | list[str], 
            to_list: bool = True
        )  -> NDArray[np.float32] | list[float] | list[list[float]]:
        """
        Generates embeddings for the input text using the pre-trained transformer model.

        Args:
            input_text (str): The input text to generate embeddings for.
            to_list (bool): Whether to return the embeddings as a list or numpy array. Defaults to True.

        Returns:
            Union[np.ndarray, list]: The embeddings generated for the input text.
        """

        try:
            embeddings = self._model.encode(input_text, show_progress_bar=False)
        except Exception:
            print(f"Error generating embeddings for {self._model_id=} and {input_text=}")
            return [] if to_list else np.array([])

        if to_list:
            embeddings = embeddings.tolist()

        return embeddings


class SparseEmbeddingModelSingleton(metaclass=SingletonPattern):
    def __init__(self, model_id: str = settings.SPARSE_EMBEDDING_MODEL_ID) -> None:
        from fastembed import SparseTextEmbedding
        self._model_id = model_id
        self._model = SparseTextEmbedding(model_name=model_id)

    @property
    def model_id(self) -> str:
        return self._model_id

    def __call__(self, texts: list[str]) -> list[dict]:
        results = list(self._model.embed(texts))
        return [
            {"indices": r.indices.tolist(), "values": r.values.tolist()}
            for r in results
        ]


class CrossEncoderModelSingleton(metaclass=SingletonPattern):
    def __init__(
        self,
        model_id: str = settings.RERANKING_CROSS_ENCODER_MODEL_ID,
        device: str = settings.RAG_MODEL_DEVICE,
    ) -> None:
        """
        A singleton class that provides a pre-trained cross-encoder model for scoring pairs of input text.
        """

        self._model_id = model_id
        self._device = device

        self._model = CrossEncoder(
            model_name=self._model_id,
            device=self._device,
            local_files_only=True,
        )
        self._model.model.eval()

    def __call__(self, pairs: list[tuple[str, str]], to_list: bool = True) -> NDArray[np.float32] | list[float]:
        scores = self._model.predict(pairs)

        if to_list:
            scores = scores.tolist()

        return scores